//
// Created by Dmitry Morozov on 18/3/23.
//

#ifndef LEVELIP_CPP_JUNIOR_HOMETASKS_WEEK_1_MENUCLASS_SRC_I_MENU_ITEM_HPP_
#define LEVELIP_CPP_JUNIOR_HOMETASKS_WEEK_1_MENUCLASS_SRC_I_MENU_ITEM_HPP_

class IMenuItem {

};

#endif //LEVELIP_CPP_JUNIOR_HOMETASKS_WEEK_1_MENUCLASS_SRC_I_MENU_ITEM_HPP_
