//
// Created by Dmitry Morozov on 18/3/23.
//

#ifndef LEVELIP_CPP_JUNIOR_HOMETASKS_WEEK_1_MENUCLASS_SRC_MENU_HPP_
#define LEVELIP_CPP_JUNIOR_HOMETASKS_WEEK_1_MENUCLASS_SRC_MENU_HPP_

class Menu {

};

#endif //LEVELIP_CPP_JUNIOR_HOMETASKS_WEEK_1_MENUCLASS_SRC_MENU_HPP_
